node('docker') {

    stage('Git checkout') {
        git branch: 'master', credentialsId: 'gihub-key', url: 'git@github.com:stuartshay/NavigatorIdentity.git'
    }


    stage('Package Diff') {
       echo "Package Diff Here  *.csproj or .json"
       echo "Call Base Image Build"
    }

    stage('Build & Deploy Docker') {
         sh '''mv docker/imagegallery-client.dockerfile/.dockerignore .dockerignore
        docker build -f docker/imagegallery-client.dockerfile/Dockerfile --build-arg BUILD_NUMBER=${BUILD_NUMBER} -t stuartshay/imagegallery-client:1.1.1-multi .'''
        withCredentials([usernamePassword(credentialsId: 'docker-hub-navigatordatastore', usernameVariable: 'DOCKER_HUB_LOGIN', passwordVariable: 'DOCKER_HUB_PASSWORD')]) {
            sh "docker login -u ${DOCKER_HUB_LOGIN} -p ${DOCKER_HUB_PASSWORD}"
        }
        sh '''docker push stuartshay/imagegallery-client:1.1.1-multi'''
    }

    stage ('Deploy to Rancher') {
        withCredentials([usernamePassword(credentialsId: 'JENKINS_ENV_KEY', passwordVariable: 'RANCHER_SECRET_KEY', usernameVariable: 'RANCHER_ACCESS_KEY')]) {
            sh 'rancher-compose --url https://rancher.navigatorglass.com/v2-beta/projects/1a5  -f docker/rancher/ImageGallery/docker-compose.yml --project-name ImageGallery up imagegallery-client --force-upgrade -p -c -d'
        }
    }

    stage('Performance metrics') {
        echo "Load Testing with apache ab"
        script {status = sh([script: "docker run --rm jordi/ab ab -n 10 -c 2 http://imagegallery-client.informationcart.com/api/Diagnostics", returnStdout: true]).trim()
         }
    }
    stage('Mail') {
        emailext attachLog: true, body: """${status}""", subject: 'Jenkins build status - imagegallery-client', to: 'sshay@yahoo.com'
    }

  //   stage('Mail') {
  //      emailext attachLog: true, body: '', subject: 'Jenkins build status - imagegallery-client', to: 'harpreet@xenondigilabs.com'
  //  }

}
